name: project_final
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  flutter_localization: ^0.2.0
  iconsax: ^0.0.8  # La nueva dependencia añadida
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  get_storage: ^2.1.1
  logger: ^2.1.0
  firebase_auth: ^4.19.5
  intl: ^0.18.1
  http: ^1.2.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
  - assets/images/on_boarding_images/
  - assets/logos/



